import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {AiFillLinkedin, AiFillGithub, AiFillTwitterCircle} from 'react-icons/ai'
import Image from 'next/image';
import headshot from 'public/headshot.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Fernando Estrada</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Fernando Estrada</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li> 
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl p-2 text-teal-600 font-medium">Fernando Estrada</h2>
            <h3 className="text-2xl py-2">Full Stack Developer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Recent Bootcamp graduate from ThriveDX. Looking to dive deep into the world of programming and bring a passion for learning to a team.</p>
          </div>
          {/* LINKS */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="#"> 
              <AiFillLinkedin />
              </a>
              <a href="#">
              <AiFillGithub />
              </a>
              <a href="#">
              <AiFillTwitterCircle />
            </a>
          </div>
          {/* HEADSHOT PHOTO */}
          <div className="">
            <Image src={headshot} alt="fernando headshot" className="mx-auto relative rounded-full w-80 h-80 mt-10"/>
          </div>
        </section> 

        <section>
          <div>
            <h3 className="text-3xl py-1">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-600">
              I have only recently began my journey into programming, yet I already know this where I want to be. This industry is full of possibilites and I am <span className="text-teal-500">ecstatic</span> for the oppurtunity to create <span className="text-teal-500">amazing</span> projects. If you are interested in connecting send me an email or even message me on Linkedin!
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
